-- MySQL Script generated by MySQL Workbench
-- 03/06/19 06:58:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coinless
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coinless
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coinless` DEFAULT CHARACTER SET utf8 ;
USE `coinless` ;

-- -----------------------------------------------------
-- Table `coinless`.`cor_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coinless`.`cor_users` (
  `userid` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birth_date` DATE NULL,
  `address` VARCHAR(150) NULL,
  `qrcode` VARCHAR(45) NOT NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Update at any login or transaction',
  `username` VARCHAR(16) NULL,
  `password` VARCHAR(32) NOT NULL,
  `urgency_code` VARCHAR(8) NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `qrcode_UNIQUE` (`qrcode` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coinless`.`cor_registers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coinless`.`cor_registers` (
  `reg_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'It will be used on detailed transactions.',
  `userid` VARCHAR(50) NOT NULL,
  `date_reg` TIMESTAMP NOT NULL,
  `cost_value` INT(10) NOT NULL COMMENT 'Montant',
  `number_days` INT(2) NOT NULL COMMENT 'Nombre de jour de l\'abonnement.',
  `reg_status` TINYINT(1) NOT NULL COMMENT 'Statut actif/non-actif de l\'abonnement',
  PRIMARY KEY (`reg_id`))
ENGINE = InnoDB
COMMENT = 'Abonnements des utilisateurs. une routine-trigger sera mise en place pour le calcul entre la date courante et celle de date_reg, faire un comparaison avec number_days et changer le status de reg_status a true ou false.';


-- -----------------------------------------------------
-- Table `coinless`.`cor_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coinless`.`cor_transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reg_id` BIGINT NOT NULL,
  `userfrom` VARCHAR(45) NOT NULL,
  `userto` VARCHAR(45) NOT NULL,
  `date_transac` TIMESTAMP NOT NULL,
  `code_transac` VARCHAR(45) NOT NULL COMMENT 'Code de la transaction',
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
